
# Text to speech
tts:
  - platform: google_translate

history:

homeassistant:
  unit_system: metric
  time_zone: Europe/Warsaw
  temperature_unit: C
  packages: !include_dir_named packages
lovelace:
  mode: yaml

config:
hassio:
python_script:

sun:
conversation:
map:

system_health:
  
logger:
  default: info
  logs:
    homeassistant.components.automation: info
    homeassistant.components.scripts: info
    homeassistant.config: info
    homeassistant.log: info
    homeassistant.components.xiaomi_aqara: fatal
    homeassistant.components.binary_sensor.xiaomi_aqara: fatal
    homeassistant.components.sensor.xiaomi_aqara: fatal
    homeassistant.components.light.xiaomi_aqara: fatal
    homeassistant.components.switch.xiaomi_aqara: fatal
    homeassistant.components.light.xiaomi_miio: fatal
    homeassistant.components.mqtt: fatal

mqtt:
    # discovery: clean
    discovery: true
    discovery_prefix: homeassistant
    broker: 127.0.0.1
    port: 1883
    client_id: homeassistant
    username: iot
    password: securne

media_player:
  - platform: samsungtv
    host: 10.122.18.154

#systemik obiadowy
lunch:
