# Example configuration entry
esphome:
  name: "ble_tracker"
  platform: ESP32
  board: nodemcu-32s
  # board_flash_mode: dout
wifi:
  ssid: "salamanders"
  password: "securnesecurne"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:
  scan_interval: 60s

binary_sensor:
  - platform: ble_presence
    mac_address: 7C:64:56:89:6F:A9
    name: "TestBLEDongle"

