sensor:
  - platform: rest
    name: GiosAir
    #curl -X GET     --header 'Accept: application/json'  http://api.gios.gov.pl/pjp-api/rest/station/sensors/295
    resource:  http://api.gios.gov.pl/pjp-api/rest/data/getData/2069
    value_template: "{{ value_json['values'][1]['value'] }}"
    icon_template: mdi:jquery
    unit_of_measurement: "μg/m3"
input_number:
  air_red:
    name: Slider
    initial: 1000
    min: 0
    max: 5000
    step: 100
automation:
  - alias: "Status Powietrza"
    initial_state: True
    trigger:
      - platform: numeric_state
        entity_id: sensor.giosair
        above: 40.0
        for:
          minutes: 15
    action:
      - service: notify.email_kanapka
        data:
          title: 'Jakość Powietrza'
          message: "Uważaj na siebie powietrze nie jest za czyste {{states.sensor.giosair.state}} PM"
  - alias: "Salka1 LED BAD"
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
    condition:
      condition: template
      value_template: '{{ sensor.salka1_air < 500}}'
    action:
      - service: light.turn_on
        data:
          brightness: 255
          rgb_color: [0, 255, 0]
          entity_id:
            - light.salkastatus
  - alias: "Salka1 LED Good"
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
    condition:
      condition: template
      value_template: '{{ sensor.salka1_air >= 500}}'
    action:
      - service: light.turn_on
        data:
          brightness: 255
          rgb_color: [255, 0, 0]
          entity_id:
            - light.salkastatus
  - alias: "Salka1 LED AAALLLL"
    initial_state: true
    trigger:
      - platform: time_pattern
        minutes: '/1'
    condition:
      condition: template
      value_template: '{{ sensor.salka1_air >= 500}}'
    action:
      - service: light.turn_on
        entity_id: light.salkastatus
        data_template:
           rgb_color: ['{% if states.sensor.salka1_air | float < states.input_number.air_red |float %}255{% else %}0{% endif %}', '{% if states.sensor.salka1_air | float < states.input_number.air_red |float %}0{% else %}255{% endif %}', '0']
