automation:
  - alias: "salka1_15min"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.button_reservation
        to: 'single'
    action:
      - service: notify.email_production_lunch
        data:
          title: 'Rezerwacja salki 1.11'
          message: "Salka zarezerwowana na najbliższe 15 minut"
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.salka1_status
  - alias: "salka1_30min"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.button_reservation
        to: 'double'
    action:
      - service: notify.email_production_lunch
        data:
          title: 'Rezerwacja salki 1.11'
          message: "Salka zarezerwowana na najbliższe 30 minut"
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.salka1_status
  - alias: "salka1_60min"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.button_reservation
        to: 'long'
    action:
      - service: notify.email_production_lunch
        data:
          title: 'Rezerwacja salki 1.11'
          message: "Salka zarezerwowana na najbliższe 60 minut"
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.salka1_status
