automation:
  - alias: "Kanapka Szop"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kanapka_1
        to: 'on'
    action:
      - service: notify.email_send
        data:
          title: 'Szop na miejscu'
          message: "Szop znajduje się przed biurem"
          data:
            images:
              - /config/www/img/szop.jpg
  - alias: "Kanapka Kuba"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kanapka_2
        to: 'on'
    action:
      - service: notify.email_send
        data:
          title: 'Tu Kuba'
          message: "TuKuba znajduje się przed biurem"
          data:
            images:
              - /config/www/img/kuba.jpg
  - alias: "Kanapka Musztarda"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.kanapka_3
        to: 'on'
    action:
      - service: notify.email_send
        data:
          title: 'Musztarda'
          message: "Musztarda znajduje się w biurze"
          data:
            images:
              - /config/www/img/musztarda.jpg

  - alias: "BLE KANAPKA"
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.testbledongle
        to: 'on'
    action:
      - service: notify.email_send
        data:
          title: 'Musztarda'
          message: "BLE - usztarda znajduje się w biurze"
          data:
            images:
              - /config/www/img/musztarda.jpg
