automation:
  - alias: "Zakomunikuje Lunch Piwnica"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: lunch.piwnica
    action:
      service: notify.email_send
      data_template:
        title: "{{ trigger.event.data.title }}"
        message: "{{ trigger.event.data.message }}"
        data:
          images:
            - /config/www/img/lunch.piwnica.jpg