automation:
  - alias: "Send Piwnica menu"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: lunch.piwnica
    action:
      service: notify.email_send
      data_template:
        title: "{{ trigger.event.data.title }}"
        message: "{{ trigger.event.data.message }}"
        data:
          images:
            - /config/www/img/lunch.piwnica.1.jpg

  - alias: "Send W Przerwie menu"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: lunch.w_przerwie
    action:
      service: notify.email_send
      data_template:
        title: "{{ trigger.event.data.title }}"
        message: "{{ trigger.event.data.message }}"
        data:
          images:
            - /config/www/img/lunch.w_przerwie.1.jpg

  - alias: "Send Solo menu"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: lunch.solo
    action:
      service: notify.email_send
      data_template:
        title: "{{ trigger.event.data.title }}"
        message: "{{ trigger.event.data.message }}"
        data:
          images:
            - /config/www/img/lunch.solo.1.jpg

  - alias: "Send Mauroski menu"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: lunch.mauroski
    action:
      service: notify.email_send
      data_template:
        title: "{{ trigger.event.data.title }}"
        message: "{{ trigger.event.data.message }}"
        data:
          images:
            - /config/www/img/lunch.mauroski.1.jpg

  - alias: "Send dziendobry menu"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: lunch.dziendobry
    action:
      service: notify.email_send
      data_template:
        title: "{{ trigger.event.data.title }}"
        message: "{{ trigger.event.data.message }}"
    
  - alias: "Send Da Antonio menu"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: lunch.antonio
    action:
      service: notify.email_send
      data_template:
        title: "{{ trigger.event.data.title }}"
        message: |
          Post z: {{ trigger.event.data.timestamp }}
          {{ trigger.event.data.message }}
          Smacznego życzy The Second Salamander
        
  - alias: "Send AHE menu"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: lunch.ahe
    action:
      service: notify.email_send
      data_template:
        title: "{{ trigger.event.data.title }}"
        message: "{{ trigger.event.data.message }}"