input_boolean:
  notify_home:
    name: Salka 1 Status
    initial: off
automation:
  - alias: room_occupied
    trigger:
      platform: state
      entity_id: binary_sensor.binary_sensor.occupancy
      to: 'on'
    action:
      input_boolean.turn_on
  - alias: room_occupied
    trigger:
      platform: state
      entity_id: binary_sensor.binary_sensor.occupancy
      to: 'off'
    action:
      input_boolean.turn_off
    #  condition:
#    condition: state
#    entity_id: input_boolean.notify_home
#    state: 'on'
