timer:
  salka1_drzwi:
    duration: '00:01:00'
  salka1_ruch:
    duration: '00:01:00'
input_boolean:
  salka1_status:
    name: Salka 1 Status
    initial: off
  salka1_door:
    name: Salka1 Door Changed
    initial: off
  salka1_motion:
    name: Salka1 Motion Changed
    initial: off
script:
  test_window:
    sequence:
      - condition: state
        entity_id: binary_sensor.salka1_window
        state: 'open'
      - service: notify.email_send
        data:
          title: 'Zamknmij okno'
          message: "W salce 1 zostalo otwarte okno {{states.binary_sensor.salka1_window.name}}"
  salka1_door:
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.salka1_door
      - wait_template: "{{ is_state('binary_sensor.salka1_door', 'off') }}"
        continue_on_timeout: 'false'
        timeout: '00:00:30'
      - service: input_boolean.turn_on
        entity_id: input_boolean.salka1_door
  salka1_motion:
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.salka1_motion
      - wait_template: "{{ is_state('binary_sensor.salka1_motion', 'off') }}"
        continue_on_timeout: 'false'
        timeout: '00:00:30'
      - service: input_boolean.turn_on
        entity_id: input_boolean.salka1_motion
  salka1_cancel:
    sequence:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.salka1_door
            state: 'on'
          - condition: state
            entity_id: input_boolean.salka1_motion
            state: 'on'
      - service: input_boolean.turn_off
        entity_id: input_boolean.salka1_status
      - service: notify.email_send
        data:
          title: 'Rezerwacja salki 1.11'
          message: "Rezerwacja anulowana z powodu braku ruchu"
automation:
  # - alias: salka1_drzwi
  #   trigger:
  #     - platform: state
  #       entity_id: input_boolean.salka1_status
  #       to: 'on'
  #       for:
  #         minutes: 5
  - alias: salka1_meeting_start
    trigger:
      - platform: state
        entity_id: input_boolean.salka1_status
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.salka1
  - alias: salka1_meeting_check
    trigger:
      - platform: state
        entity_id: input_boolean.salka1_status
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.salka1_door
      - delay: 00:01:00
      - service: script.turn_on
        entity_id: script.salka1_motion
      - service: script.turn_on
        entity_id: script.salka1_cancel
  - alias: salka1_close_windows
    trigger:
      - platform: time
        at: '18:00:00'
    condition:
      - condition: state
        entity_id: binary_sensor.salka1_window
        state: 'off'
    action:
      - service: notify.email_send
        data:
          title: 'Zamknij okno'
          message: "W salce 1 zostalo twarte okno!"
