input_boolean:
  salka1_status:
    name: Salka 1 Status
    initial: off
script:
  salka1:
    sequence:
      - wait_template: "{{ is_state('binary_sensor.salka1_door', 'on') }}"
        timeout: '00:05:00'
        continue_on_timeout: 'false'
      - wait_template: "{{ is_state('binary_sensor.salka1_motion, 'on') }}"
        timeout: '00:02:00'
        continue_on_timeout: 'false'
      - service: input_boolean.turn_off
        entity_id: input_boolean.salka1_status
      - service: notify.email_send
        data:
          title: 'Rezerwacja salki 1.11'
          message: "Rezerwacja Anulowana z powodu braku ruchu"
automation:
  - alias: salka1_meeting_start
    trigger:
      - platform: state
        entity_id: input_boolean.salka1_status
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.salka1
  - alias: salka1_close_windows
    trigger:
      - platform: time
        at: '18:00:00'
    condition:
      - condition: state
        entity_id: binary_sensor.salka1_window
        state: 'off'
    action:
      - service: notify.email_send
        data:
          title: 'Zamknij okno'
          message: "W salce 1 zostalo twarte okno!"