input_boolean:
  salka1_status:
    name: Salka 1 Status
    initial: off
script:
  test_window:
    sequence:
      - condition: state
        entity_id: binary_sensor.salka1_window
        state: 'open'
      - service: notify.email_send
        data:
          title: 'Zamknmij okno'
          message: "W salce 1 zostalo otwarte okno {{states.binary_sensor.salka1_window.name}}"
  salka1:
    sequence:
      - wait_template: "{{ is_state('binary_sensor.salka1_door', 'on') }}"
        timeout: '00:00:30'
        name: Door
        continue_on_timeout: 'true'
      - wait_template: "{{ is_state('binary_sensor.salka1_motion', 'on') }}"
        name: Motion
        timeout: '00:00:30'
        continue_on_timeout: 'true'
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.salka1_door
            state: 'off'
          - condition: state
            entity_id: binary_sensor.salka1_motion
            state: 'off'
      - service: input_boolean.turn_off
        entity_id: input_boolean.salka1_status
      - service: notify.email_send
        data:
          title: 'Rezerwacja salki 1.11'
          message: "Rezerwacja Anulowana z powodu braku ruchu"
automation:
  - alias: salka1_meeting_start
    trigger:
      - platform: state
        entity_id: input_boolean.salka1_status
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.salka1
  - alias: salka1_close_windows
    trigger:
      - platform: time
        at: '18:00:00'
    condition:
      - condition: state
        entity_id: binary_sensor.salka1_window
        state: 'off'
    action:
      - service: notify.email_send
        data:
          title: 'Zamknij okno'
          message: "W salce 1 zostalo twarte okno!"
